### ISSUE TITLE
Spurious debug message

### ISSUE THREAD

**Issue by mikesol** [jvail/glpk.js#19]
Hi!

First, thank you _so much_ for this amazing package, it's a life saver!

I'm using glpk to synchronize audio graphs in web audio (check out https://klank-hello-world.surge.sh/ for an example). The rendering is slowed down needlessly because of the following message that is printed to the console:

```bash
Long-step dual simplex will be used
```

I did a bit of digging and it looks like GLPK accidentally shipped with this message printing even when debugging is turned off. It is reported [here](https://discourse.brew.sh/t/patch-glpk-4-65-to-make-dual-simplex-warning-an-informational-message/7590), for example.

There is a patch that fixes this [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=891465;filename=simplex-warning.patch;msg=5). It's a one-liner.

I was wondering if you could please apply this patch to your local glpk distro and rebuild?

Thank you!

**Comment by jvail** [comment]
Hi @mikesol,

thank you - interesting use case :) But in your example I did not get any console message.
I have a dump of the glpk source over here https://github.com/jvail/glpk/tree/em. With the next release I plan to include it here as a submodule instead of always downloading the source. There is a branch called em. Would you mind making a PR with the patch into that branch?

It might take a few weeks till I find the time to work on version 4. But meanwhile you could maybe build it with the code from there yourself?

Jan

**Comment by mikesol** [comment]
Thanks for this!
In my example there is no longer a message because I compiled from source with the patch.
I'll make a PR now.
