### ISSUE TITLE
Variable are lower bounded at 0 ???

### ISSUE THREAD

**Issue by tomlarkworthy** [jvail/glpk.js#29]
~~~
glpk.solve({
  name: 'LP',
  objective: {
    direction: glpk.GLP_MIN,
    name: 'obj',
    vars: [{ name: 'x', coef: 1 }]
  },
  subjectTo: [
    {
      name: 'cons1',
      vars: [{ name: 'x', coef: 1.0 }],
      bnds: { type: glpk.GLP_LO, lb: -1.0 }
    }
  ]
})
~~~

should set x to -1 but x is set to 0

**Comment by jvail** [comment]
Yes, I am afraid that's correct. You can test it with glpk by exporting your lp in cplex format:

```js
fs.writeFileSync('lp', glpk.write({
  name: 'LP',
  objective: {
    direction: glpk.GLP_MIN,
    name: 'obj',
    vars: [{ name: 'x', coef: 1 }]
  },
  subjectTo: [
    {
      name: 'cons1',
      vars: [{ name: 'x', coef: 1.0 }],
      bnds: { type: glpk.GLP_LO, lb: -1.0 }
    }
  ]
}));
```

```
\* Problem: LP *\

Minimize
 obj: + x

Subject To
 cons1: + x >= -1

End
```

```bash
glpsol --lp lp
GLPSOL: GLPK LP/MIP Solver, v4.65
Parameter(s) specified in the command line:
 --lp lp
Reading problem data from 'lp'...
1 row, 1 column, 1 non-zero
9 lines were read
GLPK Simplex Optimizer, v4.65
1 row, 1 column, 1 non-zero
Preprocessing...
~     0: obj =   0.000000000e+00  infeas =  0.000e+00
OPTIMAL SOLUTION FOUND BY LP PREPROCESSOR
Time used:   0.0 secs
Memory used: 0.0 Mb (39693 bytes)
```

Don't ask me about the math details :) It's long ago that I was actively working with LPs ... Maybe search for "non-negativity constraint" in linear programing?

**Comment by tomlarkworthy** [comment]
Thank you for explaining how I can test the behaviour upstream. I guess its not a bug then!

**Comment by jvail** [comment]
I took the chance to refresh my LP knowledge and looked it up in my book. Apparently the trick is to split the variable in a positive and a negative part:

```js
{
  name: 'LP',
  objective: {
    direction: glpk.GLP_MIN,
    name: 'obj',
    vars: [{ name: 'x+', coef: 1 }, { name: 'x-', coef: -1 }]
  },
  subjectTo: [
    {
      name: 'cons1',
      vars: [{ name: 'x+', coef: 1.0 }, { name: 'x-', coef: -1.0 }],
      bnds: { type: glpk.GLP_LO, lb: -1.0 }
    }
  ]
}
```
Then it yields the desired result:

```js
{
  name: 'LP',
  time: 0,
  result: { vars: { 'x+': 0, 'x-': 1 }, dual: { cons1: 1 }, z: -1, status: 5 }
}
```

**Comment by tomlarkworthy** [comment]
Oh cool. Thanks. I will add that as a tactic

BTW you might be interested that I was porting your work into observable notebooks, https://observablehq.com/@tomlarkworthy/mip

I think it's a pretty good way of playing with MIPs. I added a symbolic rearranger so its a bit simpler to express a problem,

**Comment by jvail** [comment]
Thank you, very nice & good idea! Maybe I should to add a link to the readme. People complained that there are too little examples/documentation in this repo.

**Comment by tomlarkworthy** [comment]
yeah links are welcome. I intend to build some cool toys on top of that notebook.

In general, I think observable is a pretty good low effort way of documenting living examples, coz its trivial for users to fork and customize on top of having all the markdown. No tools to install, you can do everything in a browser. I am a super fan boy :p

**Comment by jvail** [comment]
Sure, let me know if you have new notebooks. I'll link them in the readme. I have to admit I have trouble understanding the observable UI. Maybe I have spend too much time with python notebooks...

**Comment by tomlarkworthy** [comment]
OK wil do!

maybe this will help: https://observablehq.com/@observablehq/observable-for-jupyter-users 

The big cool thing about observablehq over Jupyter is you don't need to re-run cells they figure out their dependancies and auto rerun on upstream changes.

**Comment by tomlarkworthy** [comment]
BTW, I ran my front end through a fuzzer so I am pretty confident of its robustness at rearranging formulas to fit the required form. (https://observablehq.com/@tomlarkworthy/mip)

**Comment by jvail** [comment]
Hi @tomlarkworthy, where can I find your mip code. It seems it is buried somewhere in (un)observable :) Is there an npm pkg? However, I like the api (as far as I can see)... maybe we should just merge the two projects and simply add a LP.fromJSON() method (just thinking loud...).

**Comment by tomlarkworthy** [comment]
Technically a notebook is an ES6 module and you can link to it directly but its not that straight forward. I can move it to NPM with some time. 

The mip function source is "behind" the pictured cell:-

![image](https://user-images.githubusercontent.com/1848162/134185190-9090ae45-6747-4549-abd3-519b7def41cb.png)

The imports are also clickable in Observable. The rearranger is in 
![image](https://user-images.githubusercontent.com/1848162/134185290-9e597b00-33d2-483a-a269-4943f0218294.png)

leading to 

https://observablehq.com/@tomlarkworthy/glpk-canonicalization

Other issues 
1. the front in is MIT licensed, I am following the lead of PuLP of trying to make sure backends are pluggable, so some care has to be taken with merging.
2. The front end communicates with backend via postMessage on Window, which is not direct nodejs. so that would need to be rethought.

**Comment by jvail** [comment]
Ah, found it! - thanks for the hint.

**Comment by jvail** [comment]
So here are my thoughts @tomlarkworthy (sorry if I waste your time but it seems you might be interested in these things - maybe for your next vacation project...):

The reason for creating this library (apart from running an LP in the browser w/o a backend) was that I wanted to build the LP programmatically in JS and not concatenate a long string in a math prog. language  and then feed it into glpk. Your project is a bit a step into the other direction because you offer a way to build - again - strings that are then parsed and under the hood the LP is build. One could think that is a step back because I could easily compile the cplex LP format parser (or what else is offered by glpk) into glpk and then everyone could again just use this language to define their LPs.

However, for some years - never found the time - I am thinking about creating a SLP (sequential liner program) solver from glpk.js. I "have a few problems" :) that I could solve with such a library but not with LP because those problems would require quadratic constraints. The SLP approach (not new at all...) is pretty interesting and being able to solve some quadratic problems in the browser would be, well, sorry "cool"?

And here is the connection between the two thoughts: A user-friendly SLP solver - I guess - would require some sort of math symbolic language and parser to compute derivatives / Taylor-polynoms (that is what I was trying when I tested the approach from the original paper on SLP). I'd be interested to explore this approach a bit and since you have already some sort of math parser this could be a starting point.

**Comment by tomlarkworthy** [comment]
under the hood its math.js, which does support symbolic derivatives
(https://mathjs.org/docs/reference/functions/derivative.html) 

I dunno what is Taylor polynomials but I don't think math.js has it out of the box.

It be trivial to pass math.js ASTs directly to the solver which would make sense if you used it as a component to a SLP

I too want to solve quadratic constraints, so I like the idea though this is not my #1 side project so its a bit difficult juggling the time. I think short term I wish to promote the LP in a browser solver a bit more before building a more ambitious solver. But quadratic solving would be very good for automatic diagram layouts.

We need to attract more attention for this project first I think. I want some "wow" somehow. I once used a MIP to classify OCRed tables https://edinburghhacklab.com/2013/09/probabalistic-scraping-of-plain-text-tables/ which got on hackernews twice. So that was cool.

And the other thing I think of is physics engines, matter.js is Gauss-Siedel https://github.com/liabru/matter-js/blob/master/src/constraint/Constraint.js#L140 for instance.  There is pedological value and eye candy and interation in explaining how motion constraints can be solved with LP.

But maybe you have other cool demos of LP technology?

**Comment by jvail** [comment]
> But maybe you have other cool demos of LP technology?

Yes, my demos are quite outdated and probably lack the "wow factor" (just cows..)
Could be interesting to find some spatial optimization problem to combine spatial data with LP because displaying maps gives more interesting visualizations than just boring LP output e.g. https://gistbok.ucgis.org/bok-topics/linear-programming-and-gis
Maybe I can even combine this with https://github.com/jvail/spl.js to have an example for both.

Not sure though. I have to admit I am not a great "wow business" person.

**Comment by tomlarkworthy** [comment]
I love agriculture science, but yeah, tables and line graphs do not resonate so well. Maps work well though. OK I will experiment a bit.

**Comment by jvail** [comment]
I took the chance to do all the stuff (branch `v4`) I wanted to do for a looong time. I have also added a callback to retrieve the current values at `each`: iteration (works only with simplex). There is an example in test/test.js. I think that might be helpful to create more fancy examples: e.g. to visualize the objective value moving towards an optimum.
